## Programming quiz

### Below, you'll implement a forward pass through a 4x3x2 network, with sigmoid activation functions for both layers.

Things to do:
    Calculate the input to the hidden layer.
    Calculate the hidden layer output.
    Calculate the input to the output layer.
    Calculate the output of the network.

In [2]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input  = 4
N_hidden = 3
N_output = 2
np.random.seed(42)

# Make some fake data
X = np.random.randn(4)
print('\nInputs (X):')
print(X)

weights_input_to_hidden  = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
print('\nWeights_input_to_hidden:')
print(weights_input_to_hidden)

weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
print('\nWeights_hidden_to_output:')
print(weights_hidden_to_output)



Inputs (X):
[ 0.49671415 -0.1382643   0.64768854  1.52302986]

Weights_input_to_hidden:
[[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]

Weights_hidden_to_output:
[[-0.10128311  0.03142473]
 [-0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763]]


In [7]:
# Make a forward pass through the network (hidden layer)
hidden_layer_in  = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)
print('\nHidden-layer Output:')
print(hidden_layer_out)

# Make a forward pass through the network (output layer)
output_layer_in  = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)
print('\nOutput-layer Output:')
print(output_layer_out)



Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]

Output-layer Output:
[0.49815196 0.48539772]
